// flow-typed signature: f8cbd766c36364ef36616f7fe40ea684
// flow-typed version: <<STUB>>/beepboop-botkit_v^1.4.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'beepboop-botkit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "beepboop-botkit" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "beepboop-botkit/examples/simple" {
  declare module.exports: any;
}

declare module "beepboop-botkit/lib/beepboop-botkit" {
  declare module.exports: any;
}

// Filename aliases
declare module "beepboop-botkit/examples/simple.js" {
  declare module.exports: $Exports<'beepboop-botkit/examples/simple'>;
}
declare module "beepboop-botkit/index" {
  declare module.exports: $Exports<'beepboop-botkit'>;
}
declare module "beepboop-botkit/index.js" {
  declare module.exports: $Exports<'beepboop-botkit'>;
}
declare module "beepboop-botkit/lib/beepboop-botkit.js" {
  declare module.exports: $Exports<'beepboop-botkit/lib/beepboop-botkit'>;
}
