// flow-typed signature: 8fb04cc6c13efa96e2e4709a30e234e9
// flow-typed version: <<STUB>>/beepboop-persist_v^0.1.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'beepboop-persist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'beepboop-persist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'beepboop-persist/lib/beepboop-provider' {
  declare module.exports: any;
}

declare module 'beepboop-persist/lib/fs-provider' {
  declare module.exports: any;
}

declare module 'beepboop-persist/lib/logger' {
  declare module.exports: any;
}

declare module 'beepboop-persist/lib/memory-provider' {
  declare module.exports: any;
}

declare module 'beepboop-persist/test/beepboop.test' {
  declare module.exports: any;
}

declare module 'beepboop-persist/test/fs.test' {
  declare module.exports: any;
}

declare module 'beepboop-persist/test/memory.test' {
  declare module.exports: any;
}

declare module 'beepboop-persist/test/mock-server' {
  declare module.exports: any;
}

declare module 'beepboop-persist/test/persist.test' {
  declare module.exports: any;
}

declare module 'beepboop-persist/test/provider-harness' {
  declare module.exports: any;
}

// Filename aliases
declare module 'beepboop-persist/index' {
  declare module.exports: $Exports<'beepboop-persist'>;
}
declare module 'beepboop-persist/index.js' {
  declare module.exports: $Exports<'beepboop-persist'>;
}
declare module 'beepboop-persist/lib/beepboop-provider.js' {
  declare module.exports: $Exports<'beepboop-persist/lib/beepboop-provider'>;
}
declare module 'beepboop-persist/lib/fs-provider.js' {
  declare module.exports: $Exports<'beepboop-persist/lib/fs-provider'>;
}
declare module 'beepboop-persist/lib/logger.js' {
  declare module.exports: $Exports<'beepboop-persist/lib/logger'>;
}
declare module 'beepboop-persist/lib/memory-provider.js' {
  declare module.exports: $Exports<'beepboop-persist/lib/memory-provider'>;
}
declare module 'beepboop-persist/test/beepboop.test.js' {
  declare module.exports: $Exports<'beepboop-persist/test/beepboop.test'>;
}
declare module 'beepboop-persist/test/fs.test.js' {
  declare module.exports: $Exports<'beepboop-persist/test/fs.test'>;
}
declare module 'beepboop-persist/test/memory.test.js' {
  declare module.exports: $Exports<'beepboop-persist/test/memory.test'>;
}
declare module 'beepboop-persist/test/mock-server.js' {
  declare module.exports: $Exports<'beepboop-persist/test/mock-server'>;
}
declare module 'beepboop-persist/test/persist.test.js' {
  declare module.exports: $Exports<'beepboop-persist/test/persist.test'>;
}
declare module 'beepboop-persist/test/provider-harness.js' {
  declare module.exports: $Exports<'beepboop-persist/test/provider-harness'>;
}
