// flow-typed signature: 59c4d58d318a568d3fd2d0faa09b0325
// flow-typed version: <<STUB>>/botkit_v~0.2.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'botkit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "botkit" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "botkit/examples/convo_bot" {
  declare module.exports: any;
}

declare module "botkit/examples/demo_bot" {
  declare module.exports: any;
}

declare module "botkit/examples/incoming_webhooks" {
  declare module.exports: any;
}

declare module "botkit/examples/middleware_example" {
  declare module.exports: any;
}

declare module "botkit/examples/sentiment_analysis" {
  declare module.exports: any;
}

declare module "botkit/examples/slack_app" {
  declare module.exports: any;
}

declare module "botkit/examples/slackbutton_bot_interactivemsg" {
  declare module.exports: any;
}

declare module "botkit/examples/slackbutton_bot" {
  declare module.exports: any;
}

declare module "botkit/examples/slackbutton_incomingwebhooks" {
  declare module.exports: any;
}

declare module "botkit/examples/slackbutton_slashcommand" {
  declare module.exports: any;
}

declare module "botkit/examples/team_outgoingwebhook" {
  declare module.exports: any;
}

declare module "botkit/examples/team_slashcommand" {
  declare module.exports: any;
}

declare module "botkit/facebook_bot" {
  declare module.exports: any;
}

declare module "botkit/lib/Botkit" {
  declare module.exports: any;
}

declare module "botkit/lib/console_logger" {
  declare module.exports: any;
}

declare module "botkit/lib/CoreBot" {
  declare module.exports: any;
}

declare module "botkit/lib/Facebook" {
  declare module.exports: any;
}

declare module "botkit/lib/middleware/slack_authentication" {
  declare module.exports: any;
}

declare module "botkit/lib/Slack_web_api" {
  declare module.exports: any;
}

declare module "botkit/lib/Slackbot_worker" {
  declare module.exports: any;
}

declare module "botkit/lib/SlackBot" {
  declare module.exports: any;
}

declare module "botkit/lib/storage/simple_storage" {
  declare module.exports: any;
}

declare module "botkit/lib/storage/storage_test" {
  declare module.exports: any;
}

declare module "botkit/lib/TwilioIPMBot" {
  declare module.exports: any;
}

declare module "botkit/slack_bot" {
  declare module.exports: any;
}

declare module "botkit/tests/Slack_web_api" {
  declare module.exports: any;
}

declare module "botkit/twilio_ipm_bot" {
  declare module.exports: any;
}

// Filename aliases
declare module "botkit/examples/convo_bot.js" {
  declare module.exports: $Exports<'botkit/examples/convo_bot'>;
}
declare module "botkit/examples/demo_bot.js" {
  declare module.exports: $Exports<'botkit/examples/demo_bot'>;
}
declare module "botkit/examples/incoming_webhooks.js" {
  declare module.exports: $Exports<'botkit/examples/incoming_webhooks'>;
}
declare module "botkit/examples/middleware_example.js" {
  declare module.exports: $Exports<'botkit/examples/middleware_example'>;
}
declare module "botkit/examples/sentiment_analysis.js" {
  declare module.exports: $Exports<'botkit/examples/sentiment_analysis'>;
}
declare module "botkit/examples/slack_app.js" {
  declare module.exports: $Exports<'botkit/examples/slack_app'>;
}
declare module "botkit/examples/slackbutton_bot_interactivemsg.js" {
  declare module.exports: $Exports<'botkit/examples/slackbutton_bot_interactivemsg'>;
}
declare module "botkit/examples/slackbutton_bot.js" {
  declare module.exports: $Exports<'botkit/examples/slackbutton_bot'>;
}
declare module "botkit/examples/slackbutton_incomingwebhooks.js" {
  declare module.exports: $Exports<'botkit/examples/slackbutton_incomingwebhooks'>;
}
declare module "botkit/examples/slackbutton_slashcommand.js" {
  declare module.exports: $Exports<'botkit/examples/slackbutton_slashcommand'>;
}
declare module "botkit/examples/team_outgoingwebhook.js" {
  declare module.exports: $Exports<'botkit/examples/team_outgoingwebhook'>;
}
declare module "botkit/examples/team_slashcommand.js" {
  declare module.exports: $Exports<'botkit/examples/team_slashcommand'>;
}
declare module "botkit/facebook_bot.js" {
  declare module.exports: $Exports<'botkit/facebook_bot'>;
}
declare module "botkit/lib/Botkit.js" {
  declare module.exports: $Exports<'botkit/lib/Botkit'>;
}
declare module "botkit/lib/console_logger.js" {
  declare module.exports: $Exports<'botkit/lib/console_logger'>;
}
declare module "botkit/lib/CoreBot.js" {
  declare module.exports: $Exports<'botkit/lib/CoreBot'>;
}
declare module "botkit/lib/Facebook.js" {
  declare module.exports: $Exports<'botkit/lib/Facebook'>;
}
declare module "botkit/lib/middleware/slack_authentication.js" {
  declare module.exports: $Exports<'botkit/lib/middleware/slack_authentication'>;
}
declare module "botkit/lib/Slack_web_api.js" {
  declare module.exports: $Exports<'botkit/lib/Slack_web_api'>;
}
declare module "botkit/lib/Slackbot_worker.js" {
  declare module.exports: $Exports<'botkit/lib/Slackbot_worker'>;
}
declare module "botkit/lib/SlackBot.js" {
  declare module.exports: $Exports<'botkit/lib/SlackBot'>;
}
declare module "botkit/lib/storage/simple_storage.js" {
  declare module.exports: $Exports<'botkit/lib/storage/simple_storage'>;
}
declare module "botkit/lib/storage/storage_test.js" {
  declare module.exports: $Exports<'botkit/lib/storage/storage_test'>;
}
declare module "botkit/lib/TwilioIPMBot.js" {
  declare module.exports: $Exports<'botkit/lib/TwilioIPMBot'>;
}
declare module "botkit/slack_bot.js" {
  declare module.exports: $Exports<'botkit/slack_bot'>;
}
declare module "botkit/tests/Slack_web_api.js" {
  declare module.exports: $Exports<'botkit/tests/Slack_web_api'>;
}
declare module "botkit/twilio_ipm_bot.js" {
  declare module.exports: $Exports<'botkit/twilio_ipm_bot'>;
}
